### ISSUE TITLE
deprecate 'moduleName' argument in 'scheduleEvent()'

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#86]
Because we have `current(sim)$module` we really don't need the user to specify the module name.

See 9ca5851cd98f66b89214a8ea665b8b69986f4408

**Comment by eliotmcintire** [comment]
I think we can't deprecate because a user may want to schedule and event in a different module... also, we can't have `current(sim)$moduleName` as a default because `sim` is not defined where the function is defined...

**Comment by eliotmcintire** [comment]
Indeed - the default argument must be defined in the location where the function is defined, *not* where the function is called.
```
# Doesn't work because current(sim) is undefined when the function is defined
a <- scheduleEvent(sim, 1, eventType = "init")
Error in scheduleEvent(sim, 1, eventType = "init") : 
  moduleName must be a character

# Works:
a <- scheduleEvent(sim, 1, moduleName = "test", eventType = "init")
```

I will revert the change. d735a24e13c8ccbd5020f12fda6639e8d780bd40

We can add the default internally, however:  573b397b45eb653706a7c3d08eeb325c57e2e340
(incidentally, it passed all tests because we always supply `moduleName` in current use.
